-- CreateEnum
CREATE TYPE "ItemsUnitType" AS ENUM ('ITEM', 'HOUR', 'DAY', 'WEEK', 'MONTH', 'PROJECT', 'KILO', 'GRAM', 'LITRE', 'METER', 'SQUARE_FEET', 'CASE', 'BAG', 'BOX', 'PACKS', 'BOTTLE');

-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN     "lateCharge" DOUBLE PRECISION,
ADD COLUMN     "packagingCharge" DOUBLE PRECISION,
ADD COLUMN     "tax" DOUBLE PRECISION,
ALTER COLUMN "shippingCharge" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "adjustmentFee" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "discount" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "invoiceTotal" DROP NOT NULL,
ALTER COLUMN "subTotal" DROP NOT NULL;

-- AlterTable
ALTER TABLE "InvoiceItem" ADD COLUMN     "unit" "ItemsUnitType" NOT NULL DEFAULT 'ITEM',
ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "quantity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "total" SET DATA TYPE DOUBLE PRECISION;
