import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Card from "@/components/card";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ence",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Card>{children}</Card>
      </body>
    </html>
  );
}
