import type { Metadata } from "next";
import "./globals.css";
import Card from "@/components/card";

export const metadata: Metadata = {
  title: "Ence",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Card>{children}</Card>
    </html>
  );
}
