export const Constants = {
  JOBS: {
    PROCESS_INVOICE_DATA: 'PROCESS_INVOICE_DATA',
    SEND_INVOICE_ON_WHATSAPP: 'SEND_INVOICE_ON_WHATSAPP',
    SEND_INVOICE_LINK_ON_ACCEPT_FOR_PAYMENT:
      'SEND_INVOICE_LINK_ON_ACCEPT_FOR_PAYMENT'
  }
}
