export const INVOICE_CONSTANTS = {
  JOBS: {
    INVOICE_DATA_TO_MEDIA: 'INVOICE_DATA_TO_MEDIA',
    SEND_INVOICE_ON_WHATSAPP: 'SEND_INVOICE_ON_WHATSAPP',
    SEND_INVOICE_LINK_ON_ACCEPT_FOR_PAYMENT:
      'SEND_INVOICE_LINK_ON_ACCEPT_FOR_PAYMENT'
  }
}
